spring:
  application:
    name: setuplink-sprint-boot-poc
server:
  port: 443
eureka:
  instance:
    hostname: setuplink-sprint-boot-poc.herokuapp.com
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
